var welcome_text = "<p>Welcome to the experiment. This experiment should take no longer than 30 minutes.</p> <p>Press any key to begin.</p>";

var instruction_text = "<p>Please read these instructions carefully.</p>"+"<p>This study is being conducted by Jackie Spear in the Department of Psychology. You will be asked to study a list of words, and then tested on your memory performance on these same words. At test, some of the words will be previously studied words, and some will be new. Your job will be to indicate that either yes, you did previously study a word, or no, you did not. The study is computer mediated and it takes approximately 30 minutes to complete. Also, when prompted to provide a word, respond by typing in the word 'puppy'. You will receive one credit in exchange for your participation. The researcher may be contacted by email at umspear@myumanitoba.ca.</p>"+"<p>Press any key to begin.</p>";

var attention_check_text = "Provide a word:"

var fullscreen_prompt = "<p><b>Please turn off all background audio for the experiment</b>. Do not continue until you have turned off all other audio.</p>"+"<p>Also, remain in fullscreen mode for the entire experiment. The experiment will switch to full screen mode when you press the button below. It will also record if you exit fullscreen mode.</p>"

var debrief_text = "<p>In a recognition experiment, participants discriminate words that were studied in a training list from words that were not presented in the training list. As you may have noticed, in this study the amount of word relatedness was altered, where one critical non-related word was embedded in a list of related words. We hope to obtain a well-known von Restorff Effect, where critical words have a memorial benefit when presented among a list of related words. In conjunction with this, we are going to use a computational model of natural language processing, called Latent Semantic Analysis, to derive predictions that are consistent with human performance. The ultimate goal of this research is to be able to derive predictions about distinctiveness a priori using computational models. This study contained no deception or experimental manipulation of any kind. You can learn more about this line of work from our laboratory webpage located at<b> home.cc.umanitoba.ca/~jamiesor</b>Thank you for your participation, Jackie Spear, University of Manitoba.</p> </p> <p>Press any key to finish the experiment.</p>";

var test_instruction_text = "<p>Take a rest if you need.</p>"+"<p>Next, your job will be to indicate whether you previously studied a word by pressing 'y', otherwise press 'n'. Keep your index fingers on these keys. It is important that you respond accurately but also quickly.</p>"+"<p>When you are ready press 'i' to continue.</p>";
